name: "Coverage"

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Run test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn coverage
        env:
          NODE_ENV: test
      - name: Add coverage to comment
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
