name: "Test"

on:
  push:
    branches:
      - master
    tags:
      - "!*" # Do not execute on tags
    paths:
      - src/*
      - test/*
      - "*.json"
      - yarn.lock
  pull_request:
    paths:
      - "!*.MD"

jobs:
  release:
    name: Build and run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn test
        env:
          NODE_ENV: test
